baseurl = "https://wickedchicken.github.io"
title = "Outer Haven"
copyright = "Copyright (c) 2018, all rights reserved. Theme based on <a href=\"https://github.com/gyorb/hugo-dusk\">hugo-dusk</a>."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "Mike Stipicevic"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Mike Stip's personal blog"

[params]
  github = "wickedchicken"
  twitter = "wickedchicken"

[params.colors]
  # hugo-dusk colors
  background = "#18151F" # background color for the site
  main = "#44A2CE"
  text = "#EDE5E9"
  code-quote-bg = "#44A2CE" # background color for quotes and code blocks
  copyright = "#1D4F91" # copyright text color